name: Run Tests

on: 
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        
      - name: Setup the JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '23'
          cache: maven

      - name: Debug - list files
        run: ls -la
          
      - name: Run Tests
        working-directory: ./Radar-Tracker
        run: mvn test
        
      - name: Display Test Results
        uses: dorny/test-reporter@v1
        if: ${{!cancelled()}}
        with:
          name: JUnit Tests
          path: 'Radar-Tracker/**/target/surefire-reports/*.xml'
          reporter: java-junit
  
